contract_automation/app/models/__init__.py
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

engine = create_engine("mysql+pymysql://root:hm436464@localhost:3306/contract_automation?charset=utf8")
db_session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))
Base = declarative_base()
Base.query = db_session.query_property()

def init_db():
    # import all modules here that might define models so that
    # they will be registered properly on the metadata.  Otherwise
    # you will have to import them first before calling init_db()
    from app.models import smart_contract
    Base.metadata.create_all(bind=engine)

contract_automation/app/models/smart_contract.py
from app.models import Base
from sqlalchemy import Column, Integer, String


class SmartContract(Base):
    __tablename__ = "smart_contract"
    id = Column(Integer, index=True, primary_key=True)
    origin_name = Column(String(128), index=True, unique=True)
    code_file_name = Column(String(512))


class OriginFunction(Base):
    __tablename__ = "origin_function"
    id = Column(Integer, index=True, primary_key=True)
    origin_name = Column(String(128), index=True, unique=True)
    bpmn_file_name = Column(String(512))
    code_file_name = Column(String(512))

contract_automation/app/__init__.py
from flask import Flask
from app import routes
from config import Config
from app import models


def create_app():
    app = Flask(__name__)
    routes.init_route(app)
    models.init_db()
    app.config.from_object(Config)
    return app

contract_automation/app/routes/__init__.py
from .contract_add import contract_add_bp
from .index import index_bp

def init_route(app):
    app.register_blueprint(contract_add_bp)
    app.register_blueprint(index_bp)

contract_automation/app/routes/contract_add.py
import json
import os
import uuid

from flask import Blueprint, render_template, request, redirect, url_for, session

from app.utils.xml_analyze import WorkflowHandle
from app.utils.file_option import file_save, read_new_file
from app.models.smart_contract import SmartContract, OriginFunction
from app.models import db_session


contract_add_bp = Blueprint("contract_add_bp", __name__)
func_data = None
FUNCTION_SAVE_PATH = "./static/bpmn_file/"
CONTRACT_SAVE_PATH = "./static/smart_contract_file/"

@contract_add_bp.route("/add_contract", methods=['GET', 'POST'])
def add_contract():
    """
    接收前端textarea元素的全部文本，将该文本保存为.go智能合约文件
    :return:
    """
    smart_contract_name_list = []
    func_name = request.args.get("func_name")
    global func_data
    smart_contract_obj_list = OriginFunction.query.all()

    for one_obj in smart_contract_obj_list:
        smart_contract_name_list.append(one_obj.origin_name)

    if func_name:
        if func_data:
            new_data = read_new_file(os.getcwd() + "/static/bpmn_file/" + func_name + ".go")
            func_data += "\n" "\n" + new_data
        else:
            func_data = read_new_file(os.getcwd() + "/static/bpmn_file/" + func_name + ".go")

    if request.method == "POST":
        contract_text = request.form.get("contract_text")
        if contract_text:
            file_uuid_name = uuid.uuid4()
            smart_contract_name = request.form.get("contract_name")
            file_save(CONTRACT_SAVE_PATH, smart_contract_name, "go", contract_text)
            # 数据入库
            new_record = SmartContract(origin_name=smart_contract_name,
                                        code_file_name=file_uuid_name)
            db_session.add(new_record)
            db_session.commit()
            func_data = None
        # func_data = request.values.get("func_data")

    return render_template("add_contract.html",
                           func_data=func_data,
                           smart_contract_name_list=smart_contract_name_list
                           )

@contract_add_bp.route("/function_add", methods=['GET', 'POST'])
def function_add():
    if request.method == "POST":
        json_data = request.get_data()
        data = json.loads(json_data)
        content = data["data"]
        origin_name = data["name"]

        bpmn_file_uuid_name = uuid.uuid4()
        file_save(FUNCTION_SAVE_PATH, origin_name, "bpmn", content)

        xml_analyze_obj = WorkflowHandle(f"{FUNCTION_SAVE_PATH}{origin_name}.bpmn")
        go_code_text, go_file_uuid_name = xml_analyze_obj.run()
        file_save(FUNCTION_SAVE_PATH, origin_name, "go", go_code_text)
        # 数据入库
        new_record = OriginFunction(origin_name=origin_name,
                                   bpmn_file_name=bpmn_file_uuid_name,
                                   code_file_name=go_file_uuid_name)
        db_session.add(new_record)
        db_session.commit()
        print(f"origin_name:{origin_name},"
              f" bpmn_file_name:{bpmn_file_uuid_name},"
              f" code_file_name:{go_file_uuid_name}"
              f" insert successfully")

    return ""

@contract_add_bp.route("/function_show", methods=['GET', 'POST'])
def function_show():
    # 可以通过接口的方式来实现数据显示
    func_name = request.args.get("func_name")
    print(f"func_name: {func_name}")

    return redirect(url_for("contract_add_bp.add_contract", func_name=func_name))

@contract_add_bp.route("/xml_extract/<xml_file_name>", methods=['GET', 'POST'])
def xml_extract(xml_file_name):
    if request.method == "POST":
        xml_analyze_obj = WorkflowHandle(xml_file_name)
        res_text, res_file_name = xml_analyze_obj.run()

@contract_add_bp.route("/remove_func_data", methods=['GET', 'POST'])
def remove_func_data():
    global func_data
    func_data = None

    return redirect(url_for("contract_add_bp.add_contract"))

@contract_add_bp.route("/api_test", methods=['GET', 'POST'])
def api_test():
    if request.method == "POST":
        json_data = request.get_data()
        data = json.loads(json_data)
        with open("./static/bpmn_file/test.txt", "w") as f:
            f.write(data["data"])
        print(data["name"])
    return ""

contract_automation/app/routes/index.py
from flask import Blueprint


index_bp = Blueprint("index_bp", __name__)

@index_bp.route("/")
@index_bp.route("/index")
def index():
    return ""

contract_automation/app/templates/add_contract.html
{% extends "base.html" %}


{% block head %}
  <link href="../static/css/copyright_info_add.css" rel="stylesheet">
{% endblock %}

{% block body %}

{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

  <div class="container">
      <form class="form-local" role="form" action="/add_contract" method="post">
        <div class="row g-3 align-items-center">
          <div class="col-auto">
            <label for="contract_name" class="col-form-label">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</label>
          </div>
          <div class="col-auto">
            <input type="text" id="contract_name" name="contract_name" class="form-control" aria-describedby="contractNameHelpInline">
          </div>
          <div class="col-auto">
            <span id="contractNameHelpInline" class="form-text">
            &emsp;&emsp;智能合约文件名称
            </span>
          </div>
        </div>
        <br>
        <br>
        <div class="row g-3">
        <div class="col-md-2">
          {% for smart_contract_name in smart_contract_name_list %}
            <a class="btn background-color align-center" href="{{ url_for('contract_add_bp.function_show', func_name=smart_contract_name) }}">{{smart_contract_name}}</a>
            <br>
            <br>
          {% endfor %}
        </div>
        <div class="col-md-9">
          <div class="row g-3">
            <div class="col-md-12">
              <textarea class="form-control textarea" id="contract_text" name="contract_text" rows="20" aria-describedby="data_owner_help">{% if func_data != None %}{{ func_data }}{% endif %}
              </textarea>
            </div>
          </div>
        </div>
        </div>
        <br>
        <br>
        <button type="submit" class="btn background-color align-center">生成智能合约</button>
        <a class="btn background-color align-center" href="{{ url_for('contract_add_bp.remove_func_data') }}">清空内容</a>
      </form>
    </div>

{% endblock %}

contract_automation/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>智能合约自动生成</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/headers/">
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <link href="../static/css/copyright_info_add.css" rel="stylesheet">

    {% block head  %}
    {% endblock %}
</head>
<body>
<!--<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">-->
<!--  <symbol id="bootstrap" viewBox="0 0 118 94">-->
<!--    <title>区块链版权保护应用</title>-->
<!--    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>-->
<!--  </symbol>-->
<!--  <symbol id="home" viewBox="0 0 16 16">-->
<!--    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>-->
<!--  </symbol>-->
<!--  <symbol id="speedometer2" viewBox="0 0 16 16">-->
<!--    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>-->
<!--    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>-->
<!--  </symbol>-->
<!--  <symbol id="table" viewBox="0 0 16 16">-->
<!--    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>-->
<!--  </symbol>-->
<!--  <symbol id="people-circle" viewBox="0 0 16 16">-->
<!--    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>-->
<!--    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>-->
<!--  </symbol>-->
<!--  <symbol id="grid" viewBox="0 0 16 16">-->
<!--    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>-->
<!--  </symbol>-->
<!--</svg>-->

<!--<main>-->
<!--  <div class="container">-->
<!--    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">-->
<!--      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">-->
<!--        <img src="../static/icon.jpg" alt="mdo" width="40" height="40" class="rounded-circle">-->
<!--      </a>-->

<!--      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">-->
<!--        <li><a href="#" class="nav-link px-2 link-secondary">常见问题</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 link-dark">特点</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 link-dark">首页</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 link-dark">关于</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 link-dark">联系我们&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</a></li>-->
<!--      </ul>-->
<!--        {% if username %}-->
<!--          <div class="col-md-2 dropdown text-end">-->
<!--          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            <img src="../static/user_icon/1630228748082.jpg" alt="mdo" width="32" height="32" class="rounded-circle">-->
<!--          </a>-->
<!--          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser">-->
<!--            <li><a class="dropdown-item" href="#">我的数据</a></li>-->
<!--            <li><a class="dropdown-item" href="#">个人中心</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="/logout">注销</a></li>-->
<!--          </ul>-->
<!--        </div>-->
<!--        {% else %}-->
<!--        <div class="col-md-3 text-end">-->
<!--          <button type="button" class="btn btn-outline background-color me-2">登陆</button>-->
<!--          <button type="button" class="btn background-color">注册</button>-->
<!--        </div>-->
<!--        {% endif %}-->
<!--    </header>-->
<!--  </div>-->
<!--  <div class="container">-->
<!--<div class="form-control-dark background-color form-control-dark-local">-->
<!--        <a class="btn white-font-color" href="/copyright_info_add">&emsp;&emsp;&emsp;版权数据上链&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</a>-->
<!--        <a class="btn white-font-color" href="/user_copyright_info_query">我的数据查询&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</a>-->
<!--        <a class="btn white-font-color" href="/transaction_info_query">共享数据查询&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</a>-->
<!--        <a class="btn white-font-color">数据文件上传&emsp;&emsp;&emsp;</a>-->
<!--      </div>-->
<!--  </div>-->
  {% block body %}
  {% endblock %}
    <br>
    <br>
<!--&lt;!&ndash; 底部栏  &ndash;&gt;-->
<!--    <div class="container">-->
<!--  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">-->
<!--    <p class="col-md-4 mb-0 text-muted">&copy; 2021 Company, Inc</p>-->

<!--    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">-->
<!--      <img src="../static/icon.jpg" width="50" height="50">-->
<!--    </a>-->

<!--    <ul class="nav col-md-4 justify-content-end">-->
<!--      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">首页</a></li>-->
<!--      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">特点</a></li>-->
<!--      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">常见问题</a></li>-->
<!--      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">联系我们</a></li>-->
<!--      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">关于</a></li>-->
<!--    </ul>-->
<!--  </footer>-->
<!--</div>-->

</main>
</body>
</html>

contract_automation/app/templates/basess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
 <!-- Bootstrap 的 CSS 文件 -->
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/headers/">
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <link href="../static/css/copyright_info_add.css" rel="stylesheet">
</head>
<body>

        {% block content %}
        {% endblock %}

</body>
</html>